bots_and_scores:
  BetterBot: 268240632
  STEEBot: 276067680
  HastyBot: 588506671

models:
  Linear Regression:
    class: "model.models.regression_model.RegressionModel"

cross_validation:
  cv_folds: 5
  scoring:
    rmse: "neg_root_mean_squared_error"
    mae: "neg_mean_absolute_error"
  return_train_score: true
  best_metric_key: "rmse"
