bots_and_scores:
  BetterBot: 268240632
  STEEBot: 276067680
  HastyBot: 588506671

models:
  Linear Regression:
    class: "Model.Models.regression_model.RegressionModel"

train_test_split:
  test_size: 0.2
  random_state: 42
