bots_and_scores:
  BetterBot: 268240632
  STEEBot: 276067680
  HastyBot: 588506671

models:
  Linear Regression:
    class: "model.models.regression_model.RegressionModel"
    params: {}
  XGBoost:
    class: "model.models.xgboost_model.XGBoostModel"
    params:
      n_estimators: 291
      max_depth: 10
      learning_rate: 0.017144109417060908
      subsample: 0.9007674152662399
      colsample_bytree: 0.7941578206631733
      random_state: 42
  Neural Network:
    class: "model.models.neural_network_model.NeuralNetworkModel"
    params:
      hidden_layer_sizes: [64, 32]
      activation: "tanh"
      solver: "adam"
      learning_rate_init: 0.020267548486620213
      max_iter: 300
      random_state: 42

hyperparameter_tuning:
  search_best_params: false
  trials: 5
  neural_network_search_space:
    hidden_layer_sizes: [[128, 64], [64, 32], [128, 64, 32]]
    activation: ["relu", "tanh"]
    learning_rate_init_range: [1e-5, 1e-1]
  xgboost_search_space:
    max_depth: [3, 10]
    learning_rate_range: [1e-4, 1e-1]
    n_estimators_range: [100, 500]
    subsample_range: [0.5, 1.0]
    colsample_bytree_range: [0.5, 1.0]

cross_validation:
  cv_folds: 5
  scoring:
    rmse: "neg_root_mean_squared_error"
    mae: "neg_mean_absolute_error"
  return_train_score: true
  best_metric_key: "rmse"
