data_paths:
  train: "data/source_data/train.csv"
  test: "data/source_data/test.csv"
  games: "data/source_data/games.csv"
  turns: "data/source_data/turns.csv"

output_path:
  best_model: "output/best_model.pkl"